import os

values = open("RA7table.txt").readlines()
counter = values[0].count("p")

with open('RA7table.tex', 'wb') as texfile:
 texfile.write("\\documentclass[a4paper,11pt,landscape]{article}\n")
 texfile.write("\\usepackage[landscape]{geometry}\n")
 texfile.write("\\usepackage{fixltx2e}\n")
 texfile.write("\\usepackage{hyperref}\n")
 texfile.write("\\usepackage{multirow}\n")
 texfile.write("\\begin{document}\n")
 texfile.write("\\renewcommand{\\arraystretch}{2}\n")
 texfile.write("\\begin{center}\n")
 texfile.write("\\large{Baseline selection: 3 tight leptons with $p_T > 20 / 15 / 10$ GeV, min. 2 jets, $E^{miss}_T > 50$ GeV and $M_{ll} \geq 12$ GeV}\\normalsize \\\\ \\vspace{1cm}\n")
 texfile.write("OnZ signal regions: OSSF-pair with $76 < M_{ll} < 106$ GeV \\ \\vspace{0.5cm} \\\\ \n")
 texfile.write("\\begin{tabular}{|c|c|c|c|c|}\n")
 texfile.write("\\hline \n")
 texfile.write("b-tags & $E^{miss}_T$ & $60 < H_T \leq 400$ & $400 \leq H_T < 600$ & $H_T \geq 600$\\\\ \n")
 texfile.write("\\hline \n")
 texfile.write("\\multirow{2}{*}{0 b-tags} & $50 \leq E^{miss}_T < 150$ & ")
 texfile.write(values[0])
 texfile.write(" & ")
 texfile.write(values[2])
 texfile.write(" & \multirow{7}{*}{")
 texfile.write(values[13])
 texfile.write("}\\\\ \n")
 texfile.write("\\cline{2-4} \n")
 texfile.write("& $150 \leq E^{miss}_T < 300$ & ")
 texfile.write(values[1])
 texfile.write(" & ")
 texfile.write(values[3])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{1-4}\n")
 texfile.write("\\multirow{2}{*}{1 b-tag} & $50 \leq E^{miss}_T < 150$ & ")
 texfile.write(values[4])
 texfile.write(" & ")
 texfile.write(values[6])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{2-4}\n")
 texfile.write("& $150 \leq E^{miss}_T < 300$ & ")
 texfile.write(values[5])
 texfile.write(" & ")
 texfile.write(values[7])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{1-4}\n")
 texfile.write("\\multirow{2}{*}{2 b-tags} & $50 \leq E^{miss}_T < 150$ & ")
 texfile.write(values[8])
 texfile.write(" & ")
 texfile.write(values[10])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{2-4}\n")
 texfile.write("& $150 \leq E^{miss}_T < 300$ & ")
 texfile.write(values[9])
 texfile.write(" & ")
 texfile.write(values[11])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{1-4}\n")
 texfile.write("$ \geq 3$ b-tags & $50 \leq E^{miss}_T < 300$ & \multicolumn{2}{|c|}{")
 texfile.write(values[12])
 texfile.write("} &\\\\ \n")
 texfile.write("\\hline \n")
 texfile.write("inclusive & $E^{miss}_T \geq 300$ & \multicolumn{3}{|c|}{")
 texfile.write(values[14])
 texfile.write("}\\\\ \n")
 texfile.write("\\hline \n")
 texfile.write("\\end{tabular} \\ \n")
 if counter == 3:
  texfile.write("Explanation of rates: $data : background \\pm \\sqrt{background} \\pm \\sqrt{stat^2} \\pm syst$")
 if counter == 2: 
  texfile.write("Explanation of rates: $data : signal \\pm \\sqrt{stat^2} \\pm syst$")
 texfile.write("\\newpage \n")
 texfile.write("\\large{Baseline selection: 3 tight leptons with $p_T > 20 / 15 / 10$ GeV, min. 2 jets, $E^{miss}_T > 50$ GeV and $M_{ll} \geq 12$ GeV}\\normalsize \\\\ \\vspace{1cm}\n")
 texfile.write("OffZ signal regions: OSSF-pair with $M_{ll} < 76$ GeV or $M_{ll} > 106$ GeV \\\\ \\vspace{0.5cm}\n")
 texfile.write("\\begin{tabular}{|c|c|c|c|c|}\n")
 texfile.write("\\hline \n")
 texfile.write("b-tags & $E^{miss}_T$ & $60 < H_T \leq 400$ & $400 \leq H_T < 600$ & $H_T \geq 600$\\\\ \n")
 texfile.write("\\hline \n")
 texfile.write("\\multirow{2}{*}{0 b-tags} & $50 \leq E^{miss}_T < 150$ & ")
 texfile.write(values[15])
 texfile.write(" & ")
 texfile.write(values[17])
 texfile.write(" & \multirow{7}{*}{")
 texfile.write(values[28])
 texfile.write("}\\\\ \n")
 texfile.write("\\cline{2-4} \n")
 texfile.write("& $150 \leq E^{miss}_T < 300$ & ")
 texfile.write(values[16])
 texfile.write(" & ")
 texfile.write(values[18])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{1-4}\n")
 texfile.write("\\multirow{2}{*}{1 b-tag} & $50 \leq E^{miss}_T < 150$ & ")
 texfile.write(values[19])
 texfile.write(" & ")
 texfile.write(values[21])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{2-4}\n")
 texfile.write("& $150 \leq E^{miss}_T < 300$ & ")
 texfile.write(values[20])
 texfile.write(" & ")
 texfile.write(values[22])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{1-4}\n")
 texfile.write("\\multirow{2}{*}{2 b-tags} & $50 \leq E^{miss}_T < 150$ & ")
 texfile.write(values[23])
 texfile.write(" & ")
 texfile.write(values[25])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{2-4}\n")
 texfile.write("& $150 \leq E^{miss}_T < 300$ & ")
 texfile.write(values[24])
 texfile.write(" & ")
 texfile.write(values[26])
 texfile.write(" &\\\\ \n")
 texfile.write("\\cline{1-4}\n")
 texfile.write("$ \geq 3$ b-tags & $50 \leq E^{miss}_T < 300$ & \multicolumn{2}{|c|}{")
 texfile.write(values[27])
 texfile.write("} &\\\\ \n")
 texfile.write("\\hline \n")
 texfile.write("inclusive & $E^{miss}_T \geq 300$ & \multicolumn{3}{|c|}{")
 texfile.write(values[29])
 texfile.write("}\\\\ \n")
 texfile.write("\\hline \n")
 texfile.write("\\end{tabular} \\ \n")
 if counter == 3:
  texfile.write("Explanation of rates: $data : background \\pm \\sqrt{background} \\pm \\sqrt{stat^2} \\pm syst$")
 if counter == 2: 
  texfile.write("Explanation of rates: $data : signal \\pm \\sqrt{stat^2} \\pm syst$")
 texfile.write("\\end{center}\n")
 texfile.write("\\renewcommand{\\arraystretch}{1}\n")
 texfile.write("\\end{document}\n")
 texfile.close()

os.system("pdflatex RA7table.tex")
